env:
  global:
    secure: "RryB41K5qM9ugu1GNOQACICR1Q/04XKCfAmHmRsx+mHrZOSc1WwufGgQt424wTiuF8v/nd0FLDi5wKVALEPAquhGoiMSWl9b2h+XwDSvn3IcA0JtjYdoSH0gKHSxhhXUahErvI9lcevHxYNBldxxJC7Oy4z6yxxzJVn6snCgQIzR3gefkcwkKu8eTHZrjJXbuLjSft6UAK1w4FvOLJp+HxO/SzWxQZkelWB+vhaC7ukLw31O8fo7HujQdPO4wP6WdMRuryKBqpptuUlyNMP33B1tbrg4hPgUjqeTOMQCYtVHHb6HcUTAcZtA5D5UDIbP1568xpgjiwCUVY324HFLBT/2MflEpZKTTZY6rWRWsED3qm6XLliFbIqpqatetWwaIoml7hbCDl+kc1cyjpl840zsFSA9w+Slo8R8ppmE6VVwbEXBR2wB0A7ZIi4ua7Vq/nIjhpb1LgFjzkwESTAQCYD7s+8Tl2hehFjWU+DE5ubEQtUV4jodQZdRy2MXepb5bKDwdTkawWeMP4BWBoeBQpB2gcDklJevHWv8lKgn+esFa+l84eJP8ikckpw6m3DQfe4P6k6r8qRuTCIZTNCAm9yrtLwvW0dBM/o0XAxIQjWUT1XX0dF+1HMgXLmavl/bK360IMWtnm2ZISoUmALRNY3nLu7Sp4AHNlIU6JLKT2A="

addons:
  coverity_scan:
    project:
      name: "bloodstalker/cgrep"
      description: cgrep
    notification_email: thabogre@gmail.com
    build_command_prepend:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - sudo apt-get install libstdc++-7-dev -y
      - wget https://apt.llvm.org/llvm.sh
      - chmod +x llvm.sh
      - sudo ./llvm.sh 9
      - sudo apt-get install llvm-9-dev libclang-common-9-dev libclang-9-dev libboost-system-dev libboost-filesystem-dev -y
      - git submodule init
      - git submodule update
    build_command:
      - make CXX=clang-9 LLVM_CONF=llvm-config-9
    branch_pattern: master

matrix:
  fast_finish: true
  include:
    - dist: trusty
      name: llvm5
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo add-apt-repository ppa:fkrull/deadsnakes -y
      - sudo apt-get update -y
      - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
      - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main" | sudo tee -a /etc/apt/sources.list
      - sudo apt-get update -qq
      - travis_retry sudo apt-get install clang-5.0 libclang-5.0-dev libclang-common-5.0-dev libllvm5.0 llvm-5.0-dev llvm-5.0 llvm-5.0-runtime -y
      - sudo apt-get install gcc-4.9 g++-4.9 libboost-system-dev libboost-filesystem-dev -y
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
      - git submodule init
      - git submodule update
      script:
      - make CXX=clang-5.0 LLVM_CONF=llvm-config-5.0
      after_success:
      - bash run.sh
    - dist: trusty
      name: llvm6
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
      - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main" | sudo tee -a /etc/apt/sources.list
      - sudo apt-get update -qq
      - travis_retry sudo apt-get install clang-6.0 libclang-6.0-dev libclang-common-6.0-dev libllvm6.0 llvm-6.0-dev llvm-6.0 llvm-6.0-runtime -y
      - git submodule init
      - git submodule update
      script:
      - make CXX=clang-6.0 LLVM_CONF=llvm-config-6.0
      after_success:
        - ./run.sh
    - dist: bionic
      name: llvm7
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - sudo apt-get install libstdc++-7-dev -y
      - sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository "deb http://apt.llvm.org/bionic/   llvm-toolchain-bionic-7  main"
      - sudo apt-get update
      - sudo apt-get install clang-7 llvm-7-dev libclang-common-7-dev libclang-7-dev -y
      - git submodule init
      - git submodule update
      script:
        - make CXX=clang-7 LLVM_CONF=llvm-config-7
      after_success:
        bash run.sh
    - dist: bionic
      name: llvm8
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - sudo apt-get install libstdc++-7-dev -y
      - sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository "deb http://apt.llvm.org/bionic/   llvm-toolchain-bionic-8  main"
      - sudo apt-get update
      - sudo apt-get install clang-8 llvm-8-dev libclang-common-8-dev libclang-8-dev -y
      - git submodule init
      - git submodule update
      script:
        - make CXX=clang-8 LLVM_CONF=llvm-config-8
      after_success:
        bash run.sh
    - dist: bionic
      name: llvm9
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - sudo apt-get install libstdc++-7-dev -y
      - sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository "deb http://apt.llvm.org/bionic/   llvm-toolchain-bionic-9  main"
      - sudo apt-get update
      - sudo apt-get install clang-9 llvm-9-dev libclang-common-9-dev libclang-9-dev -y
      - git submodule init
      - git submodule update
      script:
        - make CXX=clang-9 LLVM_CONF=llvm-config-9
      after_success:
        bash run.sh
    - dist: bionic
      name: llvm10
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - sudo apt-get install libstdc++-7-dev -y
      - sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository "deb http://apt.llvm.org/bionic/   llvm-toolchain-bionic-10  main"
      - sudo apt-get update
      - sudo apt-get install clang-10 llvm-10-dev libclang-common-10-dev libclang-10-dev -y
      - git submodule init
      - git submodule update
      script:
        - make CXX=clang-10 LLVM_CONF=llvm-config-10
      after_success:
        bash run.sh
    - dist: bionic
      name: llvm11
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - sudo apt-get install libstdc++-7-dev -y
      - sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - sudo add-apt-repository "deb http://apt.llvm.org/bionic/   llvm-toolchain-bionic-11  main"
      - sudo apt-get update
      - sudo apt-get install clang-11 llvm-11-dev libclang-common-11-dev libclang-11-dev -y
      - git submodule init
      - git submodule update
      script:
        - make CXX=clang-11 LLVM_CONF=llvm-config-11
      after_success:
        bash run.sh
    - dist: bionic
      name: llvm12
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - wget https://apt.llvm.org/llvm.sh
      - chmod +x llvm.sh
      - sudo ./llvm.sh 12
      - sudo apt-get install -y clang-12 llvm-12-dev libclang-common-12-dev libclang-12-dev
      - git submodule init
      - git submodule update
      script:
        - mkdir build && cd build && cmake ../ -DLLVM_CONF=llvm-config-12 -DCMAKE_CXX_COMPILER=clang++-12 -DUSE_MONOLITH_LIBTOOLING=OFF&& make -j2
    - dist: bionic
      name: llvm13
      sudo: required
      language: cpp
      before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -y
      - wget https://apt.llvm.org/llvm.sh
      - chmod +x llvm.sh
      - sudo ./llvm.sh 13
      - sudo apt-get install -y clang-13 llvm-13-dev libclang-common-13-dev libclang-13-dev
      - git submodule init
      - git submodule update
      script:
        - mkdir build && cd build && cmake ../ -DLLVM_CONF=llvm-config-13 -DCMAKE_CXX_COMPILER=clang++-13 -DUSE_MONOLITH_LIBTOOLING=OFF&& make -j2
